import localFont from "next/font/local";
import "./scss/global.scss";
import Header from "./components/header";
import StoreProvider from "@/store/storeProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
 
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="conteiner">
          <Header/>
          {children}
        </div>
      </body>
      </StoreProvider>
    </html>
  );
}
